### ISSUE TITLE
Preview on existing posts not functioning

### ISSUE THREAD

**Issue by rtablada** [wardrobecms/core-archived#9]
When attempting to view previews of existing posts, previews are empty. Will start digging into this magic of local storage to see if I can't start pub when a preview link is clicked?

**Comment by ericlbarnes** [comment]
I worked on that last night. Let me check it out and see what's going on.

**Comment by rtablada** [comment]
Cool, I'll hold on before trying to slay dragons.

**Comment by rtablada** [comment]
Not sure where you are on this, but I just thought that we may be able to kill a few birds with one stone by moving local storage stuff into a `localstorage_view` and then we can jump on some of the localstorage stuff in the list view as well.

**Comment by ericlbarnes** [comment]
Should be fixed now. 

Not sure I follow what you are thinking for local storage in the list view.

**Comment by rtablada** [comment]
Or something like a pub sub listener?

``` js
App.vent.trigger "post:item:store", @model
```

**Comment by ericlbarnes** [comment]
Still not following :frowning:

**Comment by rtablada** [comment]
I'll check it out and see if I can better state what I was thinking...

**Comment by rtablada** [comment]
I think the problem was that we weren't looking in the same views. The problem is still occurring on in the list_view. I am gonna dive in and see what I can refactor and share component wise.

Since preview storage publishing is occurring on the new, edit, and list view should this be handled in the post controller?

**Comment by ericlbarnes** [comment]
Well the controller would be tricky since new and edit both use keyup and onChange events. Adding it to the list was pretty simple.
